name: Factions
version: 1.6.0_dev
main: com.massivecraft.factions.P
authors: [Olof Larsson, Brett Flannigan]
softdepend: [PermissionsEx, Permissions, Essentials, EssentialsChat, HeroChat, iChat, LocalAreaChat, nChat, ChatManager, AuthMe, iConomy, Register, Spout, WorldEdit, WorldGuard]
permissions:
  factions.kit.admin:
    description: All faction permissions.
    children:
      factions.kit.mod: true
      factions.config: true
      factions.lock: true
      factions.reload: true
      factions.save: true
  factions.kit.mod:
    description: All faction permissions but configuration and persistance.
    children:
      factions.kit.halfmod: true
      factions.disband.any: true
      factions.setpermanent: true
      factions.setpeaceful: true
      factions.sethome.any: true
  factions.kit.halfmod:
    description: Zones, bypassing, and kicking
    children:
      factions.kit.fullplayer: true
      factions.managesafezone: true
      factions.managewarzone: true
      factions.bypass: true
      factions.kick.any: true
      factions.ownershipbypass: true
  factions.kit.fullplayer:
    description: Can also create new factions.
    children:
      factions.kit.halfplayer: true
      factions.create: true
  factions.kit.halfplayer:
    description: Can do all but create factions.
    children:
      factions.admin: true
      factions.autoclaim: true
      factions.balance: true
      factions.balance.any: true
      factions.withdraw: true
      factions.pay: true
      factions.chat: true
      factions.claim: true
      factions.deinvite: true
      factions.deposit: true
      factions.description: true
      factions.disband: true
      factions.help: true
      factions.home: true
      factions.join: true
      factions.kick: true
      factions.leave: true
      factions.list: true
      factions.map: true
      factions.mod: true
      factions.noboom: true
      factions.open: true
      factions.owner: true
      factions.ownerlist: true
      factions.power: true
      factions.power.any: true
      factions.relation: true
      factions.sethome: true
      factions.show: true
      factions.tag: true
      factions.title: true
      factions.version: true
      factions.unclaim: true
      factions.unclaimall: true
  factions.admin:
    description: hand over your admin rights
  factions.autoclaim:
    description: auto-claim land as you walk around
  factions.balance:
    description: show current faction balance
  factions.balance.any:
    description: show on other factions balance
  factions.withdraw:
    description: withdraw money from your faction bank
  factions.pay:
    description: pay another faction from your bank
  factions.bypass:
    description: enable admin bypass mode
  factions.chat:
    description: change chat mode
  factions.claim:
    description: claim the land where you are standing
  factions.config:
    description: change a conf.json setting
  factions.create:
    description: create a new faction
  factions.deinvite:
    description: remove a pending invitation
  factions.deposit:
    description: deposit money into your faction bank
  factions.description:
    description: change the faction description
  factions.disband:
    description: disband a faction
  factions.disband.any:
    description: disband an other faction
  factions.help:
    description: display a help page
  factions.home:
    description: teleport to the faction home
  factions.join:
    description: join a faction
  factions.kick:
    description: kick a player from the faction
  factions.kick.any:
    description: kick anyone from any faction
  factions.leave:
    description: leave your faction
  factions.list:
    description: see a list of the factions
  factions.lock:
    description: lock all write stuff
  factions.managesafezone:
    description: claim land as a safe zone and build/destroy within safe zones
  factions.managewarzone:
    description: claim land as a war zone and build/destroy within war zones
  factions.map:
    description: show territory map, set optional auto update
  factions.mod:
    description: give or revoke moderator rights
  factions.noboom:
    description: toggle explosions (peaceful factions only)
  factions.open:
    description: switch if invitation is required to join
  factions.owner:
    description: set ownership of claimed land
  factions.ownerlist:
    description: list owner(s) of this claimed land
  factions.ownershipbypass:
    description: bypass ownership restrictions within own faction's territory
  factions.setpeaceful:
    description: designate a faction as peaceful
  factions.setpermanent:
    description: designate a faction as permanent
  factions.power:
    description: show player power info
  factions.power.any:
    description: view an other players power level
  factions.relation:
    description: set relation wish to another faction
  factions.reload:
    description: reload data file(s) from disk
  factions.save:
    description: save all data to disk
  factions.sethome:
    description: set the faction home
  factions.sethome.any:
    description: set any faction home
  factions.show:
    description: show faction information
  factions.tag:
    description: change the faction tag
  factions.title:
    description: set or remove a players title
  factions.version:
    description: see the version of the plugin
  factions.unclaim:
    description: unclaim the land where you are standing
  factions.unclaimall:
    description: unclaim all of your factions land