name: Factions
version: 1.6.0_dev
main: com.massivecraft.factions.P
softdepend:
  - PermissionsEx
  - Permissions
  - Essentials
  - EssentialsChat
  - HeroChat
  - iChat
  - LocalAreaChat
  - nChat
  - ChatManager
  - AuthMe
  - iConomy
  - Register
  - Spout
  - WorldEdit
  - WorldGuard
permissions:
  factions.*:
    description: Grants all Factions permissions
    children:
      factions.participate: true
      factions.create: true
      factions.viewAnyPower: true
      factions.viewAnyFactionBalance: true
      factions.peacefulExplosionToggle: true
      factions.adminBypass: true
      factions.config: true
      factions.disband: true
      factions.lock: true
      factions.manageSafeZone: true
      factions.manageWarZone: true
      factions.ownershipBypass: true
      factions.reload: true
      factions.saveall: true
      factions.setPeaceful: true
      factions.setPermanent: true
      factions.commandDisable.none: true
  factions.participate:
    description: participate in a faction
    default: true
  factions.create:
    description: create a new faction
    default: true
  factions.viewAnyPower:
    description: view the power level of anyone else
    default: true
  factions.viewAnyFactionBalance:
    description: view the faction bank balance for any faction
    default: true
  factions.peacefulExplosionToggle:
    description: disable explosions in your territory as a peaceful faction admin or moderator
    default: true
  factions.adminBypass:
    description: enable admin bypass mode (build/destroy anywhere)
    default: op
  factions.config:
    description: use /f config command to change conf.json options
    default: op
  factions.manageSafeZone:
    description: claim land as a safe zone and build/destroy within safe zones
    default: op
  factions.manageWarZone:
    description: claim land as a war zone and build/destroy within war zones
    default: op
  factions.ownershipBypass:
    description: bypass ownership restrictions within own faction's territory
    default: op
  factions.reload:
    description: use the /f reload command to reload data file(s) from disk
    default: op
  factions.saveall:
    description: use the /f saveall command to save all data to disk
    default: op
  factions.setPeaceful:
    description: designate specific factions as "peaceful" (no PvP, no land stealing, etc.)
    default: op
  factions.setPermanent:
    description: designate specific factions as permanent (not disbanded even with no members)
    default: op
	
  factions.command.admin:
    description: hand over your admin rights
    default: true
  factions.command.autoClaim:
    description: auto-claim land as you walk around
    default: true
  factions.command.balance:
    description: show current faction balance
    default: true
  factions.command.withdraw:
    description: withdraw money from your faction bank
    default: true
  factions.command.pay:
    description: pay another faction from your bank
    default: true
  factions.command.chat:
    description: change chat mode
    default: true
  factions.command.claim:
    description: claim the land where you are standing
    default: true
  factions.command.config:
    description: change a conf.json setting
    default: op
  factions.command.deinvite:
    description: remove a pending invitation
    default: true
  factions.command.deposit:
    description: deposit money into your faction bank
    default: true
  factions.command.description:
    description: change the faction description
    default: true
  factions.command.disband:
    description: disband a faction
    default: true
  factions.command.disband.any:
    description: disband an other faction
    default: op
  factions.command.help:
    description: display a help page
    default: true
  factions.command.home:
    description: teleport to the faction home
    default: true
  factions.command.join:
    description: join a faction
    default: true
  factions.command.kick:
    description: kick a player from the faction
    default: true
  factions.command.kick.any:
    description: kick anyone from any faction
    default: op
  factions.command.leave:
    description: leave your faction
    default: true
  factions.command.list:
    description: see a list of the factions
    default: true
  factions.command.lock:
    description: lock all write stuff
    default: op
  factions.command.map:
    description: show territory map, set optional auto update
    default: true
  factions.command.mod:
    description: give or revoke moderator rights
    default: true