name: Factions
version: 1.3.3
main: org.mcteam.factions.Factions
softdepend:
  - Permissions
  - Essentials
  - EssentialsChat
  - HeroChat
  - iChat
commands:
  f:
    description: All of the Factions commands
    usage: See documentation.